# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1104c2729ddad3c9cfd94e55744cd1cf4828484c41a29eff81683d9359f1525c8df6b77a2a3d3db155085fd7206e4fa976556e2c94e4411dd9a804d43ab0b5db

test:
  secret_key_base: bd58bef4d0a2278d85b37b71cb64b71ffc57f454bbda45b339a8eb8f165902dacbe6f23dbdd9512e78debfb97ef63dd9cc1c1f5cddfd63f59fdcdc19ff76e7e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
